spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/kotlin-spring-boot
    password: postgres
    username: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration, classpath:db/migration-dev
  jpa:
    show-sql: true